### PR TITLE
Fixed crash in Francis's room, and managed PyConsole #ifdef directives (and some typos)

### PR DESCRIPTION
**Pull request by JohnP55**

### CODE REVIEW

**Comment by SeekyCt** [comment]
I think in general it'd be good to have a crash-prevention function that hooks on something like seq_mapChangeInit and run the checks like this there, but for now this works fine.
A couple things:
- Could this be re-targetted to the dev branch instead of main?
- Was there a need to move the ifdefs for PYCONSOLE_PROTOTYPE down in the files?

**Comment by JohnP55** [comment]
It would be interesting to fix more crashes relating to warping into rooms at the wrong time through seq_mapChangeInit. If you think it would be relevant to do, I can push a new commit using it instead of _doMapChange.

- It could be re-targetted to dev if you feel it's necessary, but I think this crash in particular is important to fix because it actually makes it hard to practice the Francis fight (Zach does it on emulator w/ a savestate specifically because of this)
- There was a need to move the ifdefs for PYCONSOLE_PROTOTYPE; By having the directive before the includes, it would check if it's defined before including the file where it's defined.
- Also some of the ifdefs were called PYCONSOLE_PROT**OY**PE, which needed to be fixed for obvious reasons.

**Comment by SeekyCt** [comment]
- The dev branch currently only has a couple tiny changes and fixes, so it'd be fine to do a release pretty much straight away with those too. It's slightly easier to merge if this goes into dev first
- You'd define PYCONSOLE_PROTOTYPE with a command line flag to the compiler rather than a header
- Yeah, typo fixes are fine of course

**Comment by JohnP55** [comment]
Moved to dev, made the hook, fixed seqdefs, everything should be ready to go

**Comment by SeekyCt** [comment]
Looks good, thanks. I'll try get a release out some time soon

**Pull request merged**
